Add app locale settings
spencerccf/app_settings pull request #183
Opened 2023-07-10 10:19 UTC by nohli

As mentioned in [this PR](https://github.com/spencerccf/app_settings/pull/179#issuecomment-1628639895)

2023-07-11 09:22 UTC, nohli commented on CHANGELOG.md
> +## 4.3.0
```suggestion
## 5.1.0
Add `AppSettingsType.appLocale` to open the app language settings (only available on Android 13 and higher).

## 5.0.0
```

2023-07-11 09:23 UTC, nohli commented on pubspec.yaml
> +version: 4.4.0
```suggestion
version: 5.1.0
```

2023-07-12 11:09 UTC, navaronbracke requested changes

2023-07-12 11:09 UTC, navaronbracke commented on android/src/main/kotlin/com/spencerccf/app_settings/AppSettingsPlugin.kt
> +  private fun openAppLocaleSettings(result: Result, asAnotherTask: Boolean = false) {
Could you add a check for the Android version and only do the `startActivity()` on Android 13+ ? That way it does not throw on unsupported Android versions.

2023-07-12 16:43 UTC, navaronbracke approved these changes

2023-08-21 15:08 UTC, nohli commented
Are there plans for merging, or do I need to change anything?

2023-08-21 15:11 UTC, navaronbracke commented
I do not have commit access, so it is up to @spencerccf to review and merge this, sorry.

You can always use a git override in the meantime, though.

2023-08-21 15:20 UTC, nohli commented
Ok thanks 🤗

That's what I'm doing, just checking up on some PRs 😊

2023-08-22 14:29 UTC, merged

2023-08-27 14:15 UTC, nohli commented
Would be cool to publish to pub.dev as well.