macOS support is added
spencerccf/app_settings pull request #202
Opened 2023-11-03 15:47 UTC by alex-melnyk

2023-11-03 21:35 UTC, navaronbracke commented on macos/app_settings.podspec
> +  s.version          = '0.0.1'
There are a bunch of default values here.

2023-11-03 21:40 UTC, navaronbracke commented on macos/Classes/AppSettingsEnums.swift
> +enum SettingsGeneral: String {
Of all these enums, only two constants can be used at the moment.

You should either provide an API to open a URL with a specific value, or remove the unused enum constants.

2023-11-03 21:41 UTC, navaronbracke requested changes
Some minor feedback about the changes.

2023-11-04 19:05 UTC, alex-melnyk commented on macos/app_settings.podspec
> +  s.version          = '0.0.1'
fixed

2023-11-04 19:05 UTC, alex-melnyk commented on macos/Classes/AppSettingsEnums.swift
> +enum SettingsGeneral: String {
fixed

2023-11-06 07:23 UTC, navaronbracke requested changes
One remark about a field in the podspec.

2023-11-06 07:23 UTC, navaronbracke commented on macos/app_settings.podspec
> +  s.author           = { 'ask.melnyk@gmail.com' => 'ask.melnyk@gmail.com' }
This should refer to the author/publisher of the plugin, not your own email address.

See https://github.com/spencerccf/app_settings/blob/master/ios/app_settings.podspec#L12

```suggestion
  s.author           = { 'spencerccf@gmail.com' => 'spencerccf@gmail.com' }
```

2023-11-06 08:01 UTC, navaronbracke approved these changes

2023-11-06 08:21 UTC, alex-melnyk commented
@navaronbracke Anyway I can't merge it, please merge and publish the next version so I can use those changes from the https://pub.dev/ repository.

2023-11-06 08:51 UTC, navaronbracke commented
@alex-melnyk you can use a git override as a workaround for now: https://dart.dev/tools/pub/dependencies#git-packages

cc @spencerccf since I do not have commit access.

2023-11-06 08:58 UTC, alex-melnyk commented
> @alex-melnyk you can use a git override as a workaround for now: https://dart.dev/tools/pub/dependencies#git-packages
> 
> 
> 
> cc @spencerccf since I do not have commit access.

Yes, I already use that way, that is why I asking for the publishing a next version with my changes, thank you.

@spencerccf Please review changes, and publish a next version.

Best regards;)

2023-12-07 09:00 UTC, alex-melnyk commented
> > @alex-melnyk you can use a git override as a workaround for now: https://dart.dev/tools/pub/dependencies#git-packages
> > cc @spencerccf since I do not have commit access.
> 
> Yes, I already use that way, that is why I asking for the publishing a next version with my changes, thank you.
> 
> @spencerccf Please review changes, and publish a next version.
> 
> Best regards 😉

@spencerccf any chance to look into this PR?

2024-02-07 00:21 UTC, merged